spring:
  application:
    name: gitlab4j-stats-demo
  datasource:
    url: jdbc:h2:mem:gitlab_stats
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
knife4j:
  enable: true
  setting:
    language: zh-CN

server:
  port: 8088

gitlab:
  api:
    url: https://gitlab.com
    token: ${GITLAB_API_TOKEN:glpat-G3qGLYrP4OQN1FnvDQdoVm86MQp1Oml5ejdlCw.01.121qvnji7}
    project-id: ${GITLAB_PROJECT_ID:76375070}